name: Build Flappy Bird APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
  uses: Digreatbrian/buildozer-action@v1.0.0
  with:
    buildozer_version: stable
    command: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FlappyBird-APK
          path: bin/*.apk
